# Site settings
title: madebyray
email: info@raymondoneill.ie
description: This website was hand crafted using [jekyll](http://jekyllrb.com) and hosted with [Github pages]() . Type is set in Brandon Grotesque and served up by [Typekit](). The website itself was built using Boubon, Sass, Compass & Neat for Grids. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: madebyray
github_username:  oneillray
instagram_username: oneillray
dribbble_username: madebyray
codepen_username: oneillray
resume_url: http://represent.io/rayoneill

# Build settings
markdown: kramdown
