# Site settings
title: madebyray
email: info@raymondoneill.ie
description: I am a Front-end Developer and Digital Designer based in Dublin, Ireland.  I am passionate about web technologies, good user experience design and providing the best possible solution to a clients business problem. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: madebyray
github_username:  oneillray
instagram_username: oneillray
dribbble_username: madebyray
spotify_username: raysayhey
skype_username: oneillray
pinterest_username: oneillray
resume_url: http://represent.io/rayoneill

# Build settings
markdown: kramdown

# Collects for other Post types
collections:
  references:
    output: true
    permalink: /references/:path/
